"""Init after enableing render_as_batch

Revision ID: 1751210409a5
Revises: 
Create Date: 2022-01-22 20:48:52.457590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1751210409a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('halfcount', sa.Integer(), nullable=True),
    sa.Column('finalcount', sa.Integer(), nullable=True),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('refreshed', sa.DateTime(), nullable=True),
    sa.Column('schockoutcount', sa.Integer(), nullable=True),
    sa.Column('fallling_dice_count', sa.Integer(), nullable=True),
    sa.Column('throw_dice_count', sa.Integer(), nullable=True),
    sa.Column('changs_of_fallling_dice', sa.Float(), nullable=True),
    sa.Column('stack_max', sa.Integer(), nullable=True),
    sa.Column('play_final', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UUID', sa.String(length=200), nullable=True),
    sa.Column('is_mail_send', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('WAITING', 'STARTED', 'ROUNDFINISCH', 'PLAYFINAL', 'GAMEFINISCH', name='status'), nullable=True),
    sa.Column('stack', sa.Integer(), nullable=True),
    sa.Column('move_user_id', sa.Integer(), nullable=True),
    sa.Column('first_user_id', sa.Integer(), nullable=True),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_UUID'), ['UUID'], unique=True)

    op.create_table('statistic',
    sa.Column('halfcount', sa.Integer(), nullable=True),
    sa.Column('finalcount', sa.Integer(), nullable=True),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('refreshed', sa.DateTime(), nullable=True),
    sa.Column('schockoutcount', sa.Integer(), nullable=True),
    sa.Column('fallling_dice_count', sa.Integer(), nullable=True),
    sa.Column('throw_dice_count', sa.Integer(), nullable=True),
    sa.Column('changs_of_fallling_dice', sa.Float(), nullable=True),
    sa.Column('stack_max', sa.Integer(), nullable=True),
    sa.Column('play_final', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usercount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('chips', sa.Integer(), nullable=True),
    sa.Column('passive', sa.Boolean(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('dice1', sa.Integer(), nullable=True),
    sa.Column('dice1_visible', sa.Boolean(), nullable=True),
    sa.Column('dice2', sa.Integer(), nullable=True),
    sa.Column('dice2_visible', sa.Boolean(), nullable=True),
    sa.Column('dice3', sa.Integer(), nullable=True),
    sa.Column('dice3_visible', sa.Boolean(), nullable=True),
    sa.Column('number_dice', sa.Integer(), nullable=True),
    sa.Column('halfcount', sa.Integer(), nullable=True),
    sa.Column('finalcount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_name'))

    op.drop_table('user')
    op.drop_table('statistic')
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_UUID'))

    op.drop_table('game')
    # ### end Alembic commands ###
