"""Remove mail feedback

Revision ID: a14364e7c0be
Revises: 1751210409a5
Create Date: 2022-01-23 18:27:18.287589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a14364e7c0be'
down_revision = '1751210409a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('is_mail_send')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_mail_send', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
